# Generated by Django 3.0.7 on 2020-07-01 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rollcallmodule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='CourseName',
        ),
        migrations.RemoveField(
            model_name='history',
            name='TermName',
        ),
    ]
